_wandb:
    value:
        cli_version: 0.28.0
        e:
            kt9olt9z79kvgjcg8l9uxb001ciejwj9:
                codePath: test_wandb.py
                codePathLocal: test_wandb.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "510737248256"
                        used: "467463684096"
                email: patrickje12@gmail.com
                executable: C:\Users\pdeck\.conda\envs\catan\python.exe
                git:
                    commit: 338aa6df2ad85466a9db3e20bedc0d327a0bd2f3
                    remote: https://github.com/pdeckers98/catan_ai.git
                gpu: NVIDIA GeForce GTX 1660 SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1408
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce GTX 1660 SUPER
                      uuid: GPU-fbe49815-f9c2-8252-21f5-ed70cd3a1019
                host: Pats-PC
                memory:
                    total: "17026187264"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\pdeck\Desktop\Python\Catan\test_wandb.py
                python: CPython 3.14.6
                root: C:\Users\pdeck\Desktop\Python\Catan
                startedAt: "2026-06-25T15:03:32.187062Z"
                writerId: kt9olt9z79kvgjcg8l9uxb001ciejwj9
        m: []
        python_version: 3.14.6
        t:
            "3":
                - 2
                - 16
            "4": 3.14.6
            "5": 0.28.0
            "8":
                - 3
            "12": 0.28.0
            "13": windows-amd64
test:
    value: true
